# Generated by Django 4.1.1 on 2022-10-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="login",
            name="title",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="TITLE it's title!"
            ),
        ),
        migrations.AlterField(
            model_name="login",
            name="url",
            field=models.URLField(unique=True, verbose_name="URL it's url!"),
        ),
    ]
